/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export declare namespace contracts {
    const CW20Base: any;
    const HopersStaking: any;
    const HopersSwapHopers: any;
    const HopersSwapOthers: any;
}
