/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CW20Base.types";
import * as _1 from "./CW20Base.client";
import * as _2 from "./CW20Base.message-composer";
import * as _3 from "./HopersStaking.types";
import * as _4 from "./HopersStaking.client";
import * as _5 from "./HopersStaking.message-composer";
import * as _6 from "./HopersSwapHopers.types";
import * as _7 from "./HopersSwapHopers.client";
import * as _8 from "./HopersSwapHopers.message-composer";
import * as _9 from "./HopersSwapOthers.types";
import * as _10 from "./HopersSwapOthers.client";
import * as _11 from "./HopersSwapOthers.message-composer";
export namespace contracts {
  export const CW20Base = { ..._0,
    ..._1,
    ..._2
  };
  export const HopersStaking = { ..._3,
    ..._4,
    ..._5
  };
  export const HopersSwapHopers = { ..._6,
    ..._7,
    ..._8
  };
  export const HopersSwapOthers = { ..._9,
    ..._10,
    ..._11
  };
}